# Generated by Django 4.1.2 on 2022-11-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbapp', '0002_rename_nmae_instrument_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
