# Generated by Django 4.1.2 on 2022-11-23 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smbapp', '0004_alter_band_title_alter_musician_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
