# Generated by Django 4.1.2 on 2022-11-23 21:17

from django.db import migrations
import smbapp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('smbapp', '0005_alter_musician_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=smbapp.fields.CaseInsensitiveCharField(max_length=100, unique=True),
        ),
    ]
