# Generated by Django 4.1.2 on 2022-12-13 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smbapp', '0007_remove_post_instrument_post_tour_dates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musician',
            new_name='MyInstruments',
        ),
        migrations.RemoveField(
            model_name='band',
            name='member',
        ),
        migrations.AddField(
            model_name='band',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='band',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
