# Generated by Django 4.1.2 on 2022-12-13 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smbapp', '0008_rename_musician_myinstruments_remove_band_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='myinstruments',
            old_name='instrument',
            new_name='instruments',
        ),
    ]
