# Generated by Django 4.1.2 on 2022-12-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smbapp', '0009_rename_title_band_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myinstruments',
            old_name='email',
            new_name='user_id',
        ),
    ]
