# Generated by Django 4.1.2 on 2022-12-14 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smbapp', '0010_rename_email_myinstruments_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='myinstruments',
            name='instruments',
        ),
        migrations.RemoveField(
            model_name='myinstruments',
            name='user_id',
        ),
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(null=True ,blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True ,blank=True, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tour_name',
            field=models.CharField(null=True ,blank=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='band',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='MyInstruments',
        ),
    ]
