# Generated by Django 4.1.2 on 2022-12-14 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smbapp', '0011_musician_remove_myinstruments_instruments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(null=True ,blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True ,blank=True, upload_to='post/images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='tour_name',
            field=models.CharField(null=True ,blank=True, max_length=100),
            preserve_default=False,
        ),
    ]
