# Generated by Django 4.1.2 on 2022-12-14 19:07

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smbapp', '0012_alter_band_creator_alter_post_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='bio_link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musician',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name=django.contrib.auth.models.User),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tour_name',
            field=models.CharField(max_length=100),
        ),
    ]
