# Generated by Django 4.1.2 on 2022-12-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbapp', '0016_alter_musician_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='avatar',
        ),
        migrations.AddField(
            model_name='musician',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
