# Generated by Django 4.1.2 on 2022-12-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smbapp', '0017_remove_musician_avatar_musician_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
